# Generated by Django 4.2 on 2024-06-23 14:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book_title', models.CharField(max_length=250)),
                ('book_name', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.FileField(default='books/pdfs/default.pdf', upload_to='books/pdfs')),
                ('image', models.ImageField(default='books/images/default.png', upload_to='books/images')),
                ('search_count', models.IntegerField(default=0)),
                ('Category', models.CharField(max_length=100)),
                ('ISBN', models.CharField(max_length=20)),
                ('Publication_Country', models.CharField(max_length=100)),
                ('Language', models.CharField(max_length=50)),
                ('Publication_Year', models.IntegerField()),
            ],
        ),
    ]
