# Generated by Django 5.2 on 2025-04-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='/media/books/images/default_file.png?version=2', upload_to='books/images'),
        ),
    ]
