# Generated by Django 5.2 on 2025-04-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_annotation',
            field=models.TextField(default='No annotation yet', max_length=2000),
        ),
    ]
