# Generated by Django 5.2 on 2025-04-06 13:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_book_book_annotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_annotation',
            field=ckeditor.fields.RichTextField(default='No annotation yet'),
        ),
    ]
