# Generated by Django 5.2 on 2025-04-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_userbook'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userbook',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='userbook',
            name='status',
            field=models.CharField(choices=[('unread', 'Unread'), ('reading', 'Reading'), ('read', 'Read'), ('planning', 'Planning')], default='unread', max_length=20),
        ),
    ]
