# Generated by Django 5.2 on 2025-04-11 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_userbook_session_key_alter_userbook_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
    ]
