# Generated by Django 5.2 on 2025-04-11 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_userbook_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
