# Generated by Django 5.2 on 2025-04-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_userbook_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
    ]
