# Generated by Django 5.2 on 2025-04-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_userbook_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
