# Generated by Django 5.2 on 2025-04-12 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_userbook_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbook',
            old_name='review',
            new_name='review_text',
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userbook')),
            ],
        ),
    ]
