# Generated by Django 5.2 on 2025-04-12 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_review_userbook_review_text_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbook',
            name='review_text',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
