# Generated by Django 5.2 on 2025-04-12 11:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_review_book_alter_review_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='review',
            field=ckeditor.fields.RichTextField(default='No review yet'),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
