# Generated by Django 5.2 on 2025-04-12 12:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_userbook_review_delete_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='review',
            field=ckeditor.fields.RichTextField(blank=True, default='No review yet', null=True),
        ),
    ]
