# Generated by Django 5.2 on 2025-04-12 12:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_userbook_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='review',
            field=ckeditor.fields.RichTextField(default='No review yet'),
        ),
    ]
