# Generated by Django 5.2 on 2025-04-18 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_bookrecommendation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookRecommendation',
        ),
    ]
