# Generated by Django 5.2 on 2025-04-22 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_delete_bookrecommendation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbook',
            name='session_key',
        ),
    ]
