# Generated by Django 5.2 on 2025-04-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='subgenre',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
