# Generated by Django 5.2 on 2025-04-25 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_book_subgenre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='subgenre',
        ),
    ]
