# Generated by Django 5.2 on 2025-05-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(default='/media/profile_photos/default_profile_photo.jpg', upload_to='profile_photos/'),
        ),
    ]
